name: Build Core ohb
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.version.outputs.version}}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: get latest go version
        id: go_version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT
      - name: setup go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21.5

      - name: get sing-box version
        id: version
        run: |
          git remote add sekai https://github.com/SagerNet/sing-box.git
          git fetch --tags sekai
          version=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          echo version=$version >> $GITHUB_OUTPUT
  build-android:
    runs-on: ubuntu-latest
    needs: version
    strategy:
      matrix:
        jobs:
          - { goarch: '386', ndk: i686-linux-android34, output: '386' }
          - { goarch: arm, ndk: armv7a-linux-androideabi34, output: armeabi-v7a }
          - { goarch: arm64, ndk: aarch64-linux-android34, output: arm64-v8a }
          - { goarch: amd64, ndk: x86_64-linux-android34, output: x86_64 }
    env:
      NDK: ${{matrix.jobs.ndk}}
      GOOS: android
      NAME: ${{matrix.jobs.output}}
      TAGS: with_quic,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_reality_server,with_clash_api,with_gvisor
      GOARM: '7'
      GOARCH: ${{matrix.jobs.goarch}}
      VERSION: ${{needs.version.outputs.version}}
      CGO_ENABLED: '1'
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: get latest go version
        id: go_version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT
      - name: setup go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ${{steps.go_version.outputs.go_version}}

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: checkout sing repository
        uses: actions/checkout@v4.1.1
        with:
          ref: fix-interface
          path: sing
          repository: PuerNya/sing

      - name: replace sing
        run: |
          sed -i 's/^\/\/replace github.com.*$/replace github.com\/sagernet\/sing => .\/sing/' go.mod
      - name: build core
        env:
          CC: ${{steps.setup-ndk.outputs.ndk-path}}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{env.NDK}}-clang
        run: |
          go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" -tags "${TAGS}" ./cmd/sing-box
      - name: upload core
        uses: actions/upload-artifact@v3
        with:
          name: sing-box-${{env.VERSION}}-android-${{env.NAME}}
          path: |
            sing-box
        
